// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGNXDM8_bX1lztoD70BFyZ2qlk4PvziU8',
    appId: '1:330871937318:web:d4f31865d8c0e924d0c9e7',
    messagingSenderId: '330871937318',
    projectId: 'roastplus-app',
    authDomain: 'roastplus-app.firebaseapp.com',
    storageBucket: 'roastplus-app.firebasestorage.app',
    // measurementId: 'G-37TB0Z23XQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGNXDM8_bX1lztoD70BFyZ2qlk4PvziU8',
    appId: '1:330871937318:android:92967163c2b52892d0c9e7',
    messagingSenderId: '330871937318',
    projectId: 'roastplus-app',
    storageBucket: 'roastplus-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGNXDM8_bX1lztoD70BFyZ2qlk4PvziU8',
    appId: '1:330871937318:ios:92967163c2b52892d0c9e7',
    messagingSenderId: '330871937318',
    projectId: 'roastplus-app',
    storageBucket: 'roastplus-app.firebasestorage.app',
    androidClientId:
        '330871937318-84qipi741b1mjb42nl4uu9d9e799ol11.apps.googleusercontent.com',
    iosClientId:
        '330871937318-65hi6fpa3h2jef9dl8k7eaoi2sprne9k.apps.googleusercontent.com',
    iosBundleId: 'com.ikcoding.roastplus',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBGNXDM8_bX1lztoD70BFyZ2qlk4PvziU8',
    appId: '1:330871937318:ios:92967163c2b52892d0c9e7',
    messagingSenderId: '330871937318',
    projectId: 'roastplus-app',
    storageBucket: 'roastplus-app.firebasestorage.app',
    androidClientId:
        '330871937318-84qipi741b1mjb42nl4uu9d9e799ol11.apps.googleusercontent.com',
    iosClientId:
        '330871937318-65hi6fpa3h2jef9dl8k7eaoi2sprne9k.apps.googleusercontent.com',
    iosBundleId: 'com.ikcoding.roastplus',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBGNXDM8_bX1lztoD70BFyZ2qlk4PvziU8',
    appId: '1:330871937318:web:92967163c2b52892d0c9e7',
    messagingSenderId: '330871937318',
    projectId: 'roastplus-app',
    authDomain: 'roastplus-app.firebaseapp.com',
    storageBucket: 'roastplus-app.firebasestorage.app',
    // measurementId: 'G-37TB0Z23XQ',
  );
}
