// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase project.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not configured for this platform. '
          'You can reconfigure this by running the FlutterFire CLI again.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvEoRO0iUbKLtaBhqUxJG7vic6CNjU-R4',
    appId: '1:330871937318:web:1f5c8d4e9b8a2c3d4e5f6a7',
    messagingSenderId: '330871937318',
    projectId: 'roastplus-app',
    authDomain: 'roastplus-app.firebaseapp.com',
    storageBucket: 'roastplus-app.firebasestorage.app',
    measurementId: 'G-XXXXXXXXXX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvEoRO0iUbKLtaBhqUxJG7vic6CNjU-R4',
    appId: '1:330871937318:android:f9f18c41f7aa541ad0c9e7',
    messagingSenderId: '330871937318',
    projectId: 'roastplus-app',
    storageBucket: 'roastplus-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvEoRO0iUbKLtaBhqUxJG7vic6CNjU-R4',
    appId: '1:330871937318:ios:f9f18c41f7aa541ad0c9e7',
    messagingSenderId: '330871937318',
    projectId: 'roastplus-app',
    storageBucket: 'roastplus-app.firebasestorage.app',
    iosBundleId: 'com.ikcoding.roastplus',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCvEoRO0iUbKLtaBhqUxJG7vic6CNjU-R4',
    appId: '1:330871937318:macos:f9f18c41f7aa541ad0c9e7',
    messagingSenderId: '330871937318',
    projectId: 'roastplus-app',
    storageBucket: 'roastplus-app.firebasestorage.app',
    iosBundleId: 'com.ikcoding.roastplus',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCvEoRO0iUbKLtaBhqUxJG7vic6CNjU-R4',
    appId: '1:330871937318:windows:f9f18c41f7aa541ad0c9e7',
    messagingSenderId: '330871937318',
    projectId: 'roastplus-app',
    storageBucket: 'roastplus-app.firebasestorage.app',
  );
}
