// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfk6xs4N35cdVXWXE_UAIylcPgrX3w4WU',
    appId: '1:781258244482:web:cbcaba8a1604caa0d58f9b',
    messagingSenderId: '781258244482',
    projectId: 'bysnlogapp',
    authDomain: 'bysnlogapp.firebaseapp.com',
    storageBucket: 'bysnlogapp.firebasestorage.app',
    measurementId: 'G-XLEGLN9L2K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDcKAdqrCS9p7l7sTVxKQUUsEUu97eE_1M',
    appId: '1:781258244482:android:a50fe4967c4fee02d58f9b',
    messagingSenderId: '781258244482',
    projectId: 'bysnlogapp',
    storageBucket: 'bysnlogapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAo6DWzmD7nXY9Lb4mnS51cOxfDT-gC6rM',
    appId: '1:781258244482:ios:c45b64301e3eb7fad58f9b',
    messagingSenderId: '781258244482',
    projectId: 'bysnlogapp',
    storageBucket: 'bysnlogapp.firebasestorage.app',
    androidClientId: '781258244482-84qipi741b1mjb42nl4uu9d9e799ol11.apps.googleusercontent.com',
    iosClientId: '781258244482-65hi6fpa3h2jef9dl8k7eaoi2sprne9k.apps.googleusercontent.com',
    iosBundleId: 'com.example.roastplus',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAo6DWzmD7nXY9Lb4mnS51cOxfDT-gC6rM',
    appId: '1:781258244482:ios:c45b64301e3eb7fad58f9b',
    messagingSenderId: '781258244482',
    projectId: 'bysnlogapp',
    storageBucket: 'bysnlogapp.firebasestorage.app',
    androidClientId: '781258244482-84qipi741b1mjb42nl4uu9d9e799ol11.apps.googleusercontent.com',
    iosClientId: '781258244482-65hi6fpa3h2jef9dl8k7eaoi2sprne9k.apps.googleusercontent.com',
    iosBundleId: 'com.example.roastplus',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDfk6xs4N35cdVXWXE_UAIylcPgrX3w4WU',
    appId: '1:781258244482:web:ebf7be16b0ea7e02d58f9b',
    messagingSenderId: '781258244482',
    projectId: 'bysnlogapp',
    authDomain: 'bysnlogapp.firebaseapp.com',
    storageBucket: 'bysnlogapp.firebasestorage.app',
    measurementId: 'G-QJSVBBTXW1',
  );

}