import 'package:flutter/material.dart';
import 'package:shared_preferences/shared_preferences.dart';
import 'dart:convert';
import 'package:bysnapp/main.dart';
import 'package:bysnapp/pages/roast/roast_scheduler_tab.dart';
import 'package:intl/intl.dart';
import 'package:bysnapp/pages/roast/roast_timer_page.dart';
import 'package:bysnapp/pages/roast/roast_record_page.dart';
import 'package:bysnapp/pages/roast/roast_advisor_page.dart';
import 'package:bysnapp/pages/roast/roast_timer_page.dart';
import 'package:bysnapp/models/roast_schedule_models.dart';
import 'package:bysnapp/models/roast_break_time.dart';
import 'package:provider/provider.dart';
import '../../models/roast_schedule_form_provider.dart';
import '../../services/todayschedule_firestore_service.dart';
import '../../models/theme_settings.dart';

class RoastSchedulerTab extends StatefulWidget {
  final List<RoastBreakTime> breakTimes;
  const RoastSchedulerTab({super.key, this.breakTimes = const []});

  @override
  State<RoastSchedulerTab> createState() => RoastSchedulerTabState();
}

// --- 追加: スケジュール保存用 ---
class RoastScheduleResultModel {
  final String? type;
  final String? roastLevel;
  final List<int>? weights;
  final String? time; // "HH:mm" 形式
  final bool afterPurge;

  RoastScheduleResultModel({
    this.type,
    this.roastLevel,
    this.weights,
    this.time,
    this.afterPurge = false,
  });

  Map<String, dynamic> toJson() => {
    'type': type,
    'roastLevel': roastLevel,
    'weights': weights,
    'time': time,
    'afterPurge': afterPurge,
  };

  static RoastScheduleResultModel fromJson(Map<String, dynamic> json) {
    return RoastScheduleResultModel(
      type: json['type'] as String?,
      roastLevel: json['roastLevel'] as String?,
      weights: (json['weights'] as List?)?.map((e) => e as int).toList(),
      time: json['time'] as String?,
      afterPurge: json['afterPurge'] as bool? ?? false,
    );
  }
}

class RoastSchedulerTabState extends State<RoastSchedulerTab>
    with AutomaticKeepAliveClientMixin {
  // 修正: 存在しない型 _RoastBeanInput を仮の Map で代用
  // 存在しない型を修正し、仮のMap型で統一
  // var _beans = <RoastBeanInput>[RoastBeanInput()];
  TimeOfDay? _amStart;
  TimeOfDay? _pmStart;
  final List<RoastScheduleResult> _result = [];
  final List<List<int>> _combResults = [];
  String _overflowMsg = '';
  String _inputErrorMsg = ''; // 入力エラー用

  // --- 追加: スケジュール保存用 ---
  List<RoastScheduleResultModel> _savedSchedule = [];
  List<RoastScheduleResultModel> _savedPmSchedule = [];
  String _savedOverflowMsg = '';
  bool _restored = false;

  // スケジュール生成結果をFutureで管理
  Future<RoastScheduleData>? _futureResult;

  // 焙煎度合いアイコンマップ
  final Map<String, String> _roastIcons = {
    '浅煎り': '🌱',
    '中煎り': '🍃',
    '中深煎り': '☕',
    '深煎り': '🔥',
  };

  @override
  void initState() {
    super.initState();
    _restoreInputState().then((_) async {
      await _restoreSchedule();
      // 追加: 自動生成済みフラグがあれば_futureResultを再セット
      final prefs = await SharedPreferences.getInstance();
      final isAutoGenerated =
          prefs.getBool('roastSchedule_autoGenerated') ?? false;
      if (isAutoGenerated && _amStart != null) {
        setState(() {
          final provider = Provider.of<RoastScheduleFormProvider>(
            context,
            listen: false,
          );
          _futureResult = _calcSchedule(provider.beans, _amStart!, _pmStart);
        });
      }
    });
  }

  Future<void> _restoreSchedule() async {
    if (_restored) return;
    _restored = true;
    try {
      final prefs = await SharedPreferences.getInstance();
      final amJson = prefs.getString('roastSchedule_am');
      final pmJson = prefs.getString('roastSchedule_pm');
      final overflowMsg = prefs.getString('roastSchedule_overflow') ?? '';
      if (amJson != null) {
        final List<dynamic> amList = json.decode(amJson);
        _savedSchedule = amList
            .map((e) => RoastScheduleResultModel.fromJson(e))
            .toList();
      } else {
        _savedSchedule = [];
      }
      if (pmJson != null) {
        final List<dynamic> pmList = json.decode(pmJson);
        _savedPmSchedule = pmList
            .map((e) => RoastScheduleResultModel.fromJson(e))
            .toList();
      } else {
        _savedPmSchedule = [];
      }
      setState(() {
        _savedOverflowMsg = overflowMsg;
      });
    } catch (e) {
      setState(() {
        _savedSchedule = [];
        _savedPmSchedule = [];
        _savedOverflowMsg = '';
      });
    }
  }

  Future<void> _saveSchedule(
    List<RoastScheduleResult> am,
    List<RoastScheduleResult> pm,
    String overflowMsg,
  ) async {
    try {
      final prefs = await SharedPreferences.getInstance();
      final amList = am
          .map(
            (r) => RoastScheduleResultModel(
              type: r.task?.type,
              roastLevel: r.task?.roastLevel,
              weights: r.task?.weights,
              time: r.time != null
                  ? '${r.time!.hour.toString().padLeft(2, '0')}:${r.time!.minute.toString().padLeft(2, '0')}'
                  : null,
              afterPurge: r.afterPurge,
            ).toJson(),
          )
          .toList();
      final pmList = pm
          .map(
            (r) => RoastScheduleResultModel(
              type: r.task?.type,
              roastLevel: r.task?.roastLevel,
              weights: r.task?.weights,
              time: r.time != null
                  ? '${r.time!.hour.toString().padLeft(2, '0')}:${r.time!.minute.toString().padLeft(2, '0')}'
                  : null,
              afterPurge: r.afterPurge,
            ).toJson(),
          )
          .toList();
      await prefs.setString('roastSchedule_am', json.encode(amList));
      await prefs.setString('roastSchedule_pm', json.encode(pmList));
      await prefs.setString('roastSchedule_overflow', overflowMsg);

      setState(() {
        _savedSchedule = amList
            .map((e) => RoastScheduleResultModel.fromJson(e))
            .toList();
        _savedPmSchedule = pmList
            .map((e) => RoastScheduleResultModel.fromJson(e))
            .toList();
        _savedOverflowMsg = overflowMsg;
      });
      // Firestore自動保存は削除
    } catch (e) {
      // 失敗時は何もしない（空リスト扱い）
    }
  }

  void _addBean() {
    final provider = Provider.of<RoastScheduleFormProvider>(
      context,
      listen: false,
    );
    provider.addBean(RoastScheduleBean(name: '', weight: 0));
  }

  void _removeBean(int index) {
    final provider = Provider.of<RoastScheduleFormProvider>(
      context,
      listen: false,
    );
    provider.removeBean(index);
  }

  void _moveBean(int oldIndex, int newIndex) {
    setState(() {
      final provider = Provider.of<RoastScheduleFormProvider>(
        context,
        listen: false,
      );
      final beansCopy = List<RoastScheduleBean>.from(provider.beans);
      final item = beansCopy.removeAt(oldIndex);
      beansCopy.insert(newIndex, item);
      provider.setBeans(beansCopy);
    });
    _saveInputState();
  }

  Future<void> _pickTime(bool isAm) async {
    final picked = await showTimePicker(
      context: context,
      initialTime: TimeOfDay(hour: isAm ? 10 : 13, minute: 30),
    );
    if (picked != null) {
      setState(() {
        if (isAm) {
          _amStart = picked;
        } else {
          _pmStart = picked;
        }
      });
      _saveInputState();
    }
  }

  Future<void> _generateSchedule() async {
    setState(() {
      _overflowMsg = '';
      _inputErrorMsg = '';
      _futureResult = null;
    });

    // 入力チェック
    final provider = Provider.of<RoastScheduleFormProvider>(
      context,
      listen: false,
    );
    final beans = provider.beans
        .where(
          (b) =>
              b.name.trim().isNotEmpty &&
              b.weight > 0 &&
              b.bags != null &&
              b.bags! > 0 &&
              b.roastLevel != null &&
              b.roastLevel!.isNotEmpty,
        )
        .toList();
    if (beans.isEmpty || beans.length != provider.beans.length) {
      setState(() {
        _inputErrorMsg = 'すべての項目（豆の種類・重さ・袋数・焙煎度合い）を正しく入力してください。';
        _futureResult = null;
      });
      return;
    }
    if (_amStart == null && _pmStart == null) {
      setState(() {
        _inputErrorMsg = '午前または午後の焙煎開始時刻を選択してください。';
        _futureResult = null;
      });
      return;
    }

    int totalRoastCount = beans.fold(0, (sum, b) => sum + (b.bags ?? 0));
    const int amMax = 3;
    if (_amStart != null && (_pmStart == null || totalRoastCount <= amMax)) {
      setState(() {
        _futureResult = _calcSchedule(beans, _amStart!, null);
      });
      _futureResult!.then((data) async {
        await _saveSchedule(data.amResult, data.pmResult, data.overflowMsg);
        final prefs = await SharedPreferences.getInstance();
        prefs.setBool('roastSchedule_autoGenerated', true);
      });
      return;
    }
    if (_pmStart != null && _amStart == null) {
      setState(() {
        _futureResult = _calcSchedule(beans, _pmStart!, _pmStart);
      });
      _futureResult!.then((data) async {
        await _saveSchedule([], data.pmResult, data.overflowMsg);
        final prefs = await SharedPreferences.getInstance();
        prefs.setBool('roastSchedule_autoGenerated', true);
      });
      return;
    }
    if (_amStart != null && _pmStart != null) {
      setState(() {
        _futureResult = _calcSchedule(beans, _amStart!, _pmStart);
      });
      _futureResult!.then((data) async {
        await _saveSchedule(data.amResult, data.pmResult, data.overflowMsg);
        final prefs = await SharedPreferences.getInstance();
        prefs.setBool('roastSchedule_autoGenerated', true);
      });
      return;
    }
  }

  /// 午後の開始時刻がnullなら午前分だけ生成
  Future<RoastScheduleData> _calcSchedule(
    List<RoastScheduleBean> beans,
    TimeOfDay amStart,
    TimeOfDay? pmStart,
  ) async {
    // 1. 「豆＋焙煎度合い」でグループ化
    Map<String, List<RoastScheduleBean>> grouped = {};
    for (final b in beans) {
      final key = '${b.name}__${b.roastLevel}';
      grouped.putIfAbsent(key, () => []).add(b);
    }

    // 2. 各グループで重さごとに袋を展開
    List<RoastTask> tasks = [];
    for (final group in grouped.values) {
      List<int> allWeights = [];
      for (final b in group) {
        for (int i = 0; i < (b.bags ?? 0); i++) {
          allWeights.add(b.weight ?? 0);
        }
      }
      // 2袋ずつペアにして1枠に詰める
      int idx = 0;
      while (idx < allWeights.length) {
        List<int> pair = [];
        pair.add(allWeights[idx]);
        if (idx + 1 < allWeights.length) {
          pair.add(allWeights[idx + 1]);
        }
        tasks.add(
          RoastTask(
            type: group.first.name,
            roastLevel: group.first.roastLevel ?? '',
            weights: List.from(pair),
          ),
        );
        idx += 2;
      }
    }

    // 3. 最大6枠・12袋まで
    int totalBags = tasks.fold(0, (sum, t) => sum + t.weights.length);
    String overflowMsg = '';
    if (tasks.length > 6 || totalBags > 12) {
      overflowMsg = '1日最大12袋（6枠）までです。本日中に焙煎できない豆があります。';
      // 超過分はカット
      int allowed = 12;
      List<RoastTask> limited = [];
      for (final t in tasks) {
        if (allowed <= 0) break;
        int c = t.weights.length;
        if (c > allowed) c = allowed;
        limited.add(
          RoastTask(
            type: t.type,
            roastLevel: t.roastLevel,
            weights: t.weights.sublist(0, c),
          ),
        );
        allowed -= c;
      }
      tasks = limited;
    }

    // 4. 午前・午後分割をやめ、時系列で割り当て
    List<RoastScheduleResult> amResult = [];
    List<RoastScheduleResult> pmResult = [];
    TimeOfDay? t = amStart != null ? _addMinutes(amStart, 30) : null;
    bool switchedToPm = false;
    for (int i = 0; i < tasks.length; i++) {
      if (t == null) continue;
      // 休憩時間帯に重なる限りtを休憩終了時刻に進める
      while (true) {
        final breakInfo = _findBreak(t!);
        if (breakInfo == null) break;
        t = breakInfo.end;
      }
      // 13:00以降は必ず午後枠にする
      bool isPm = false;
      final tMinutes = t.hour * 60 + t.minute;
      if (pmStart != null) {
        final pmStartMinutes = pmStart.hour * 60 + pmStart.minute;
        if (tMinutes >= pmStartMinutes) {
          isPm = true;
          switchedToPm = true;
          t = tMinutes == pmStartMinutes ? pmStart : t;
        }
      }
      // 12:00以降は必ず午後枠にする
      final noonMinutes = 12 * 60;
      if (!isPm && tMinutes >= noonMinutes) {
        isPm = true;
        switchedToPm = true;
        if (pmStart != null) {
          t = tMinutes < pmStart.hour * 60 + pmStart.minute ? pmStart : t;
        }
      }
      // 13:00以降は必ず午後枠にする（厳密に13:00未満のみamResultに追加）
      final onePmMinutes = 13 * 60;
      if (!isPm && tMinutes >= onePmMinutes) {
        isPm = true;
        switchedToPm = true;
        if (pmStart != null) {
          t = tMinutes < pmStart.hour * 60 + pmStart.minute ? pmStart : t;
        }
      }
      // 休憩時間帯に入っているか
      final breakInfo = _findBreak(t);
      if (!isPm && breakInfo != null) {
        // 休憩明けにtを進めて午前枠のまま続行
        t = breakInfo.end;
        // もしpmStart以降になったら午後枠に切り替え
        if (pmStart != null) {
          final tMinutes = t.hour * 60 + t.minute;
          final pmStartMinutes = pmStart.hour * 60 + pmStart.minute;
          if (tMinutes >= pmStartMinutes) {
            isPm = true;
            switchedToPm = true;
            t = pmStart;
          }
        }
      }
      if (isPm) {
        // 午後枠
        if (pmStart != null) {
          final tMinutes = t.hour * 60 + t.minute;
          final pmStartMinutes = pmStart.hour * 60 + pmStart.minute;
          if (tMinutes < pmStartMinutes + 30) {
            t = _addMinutes(pmStart, 30);
          }
        }
        bool pmInBreak = widget.breakTimes.any((b) {
          final tMinutes = t!.hour * 60 + t.minute;
          final breakStart = b.start.hour * 60 + b.start.minute;
          return tMinutes >= (breakStart - 10) &&
              tMinutes < b.end.hour * 60 + b.end.minute;
        });
        while (pmInBreak) {
          if (t == null) break;
          t = _addMinutes(t, 20);
          pmInBreak = widget.breakTimes.any((b) {
            final tMinutes = t!.hour * 60 + t.minute;
            final breakStart = b.start.hour * 60 + b.start.minute;
            return tMinutes >= (breakStart - 10) &&
                tMinutes < b.end.hour * 60 + b.end.minute;
          });
        }
        pmResult.add(RoastScheduleResult(task: tasks[i], time: t));
        // 2回目以降は常に20分間隔
        t = _addMinutes(t!, 20);
      } else {
        // 午前枠
        amResult.add(RoastScheduleResult(task: tasks[i], time: t));
        // 常に20分間隔
        t = _addMinutes(t, 20);
      }
    }
    // 午前・午後両方の最後に必ずアフターパージを追加
    if (amResult.isEmpty || !amResult.last.afterPurge) {
      amResult.add(
        RoastScheduleResult(task: null, time: null, afterPurge: true),
      );
    }
    if (pmResult.isEmpty || !pmResult.last.afterPurge) {
      pmResult.add(
        RoastScheduleResult(task: null, time: null, afterPurge: true),
      );
    }

    // 6. 余り豆組み合わせ案（省略：現状通り）

    return RoastScheduleData(amResult, pmResult, [], overflowMsg);
  }

  TimeOfDay _addMinutes(TimeOfDay t, int min) {
    final dt = DateTime(
      2020,
      1,
      1,
      t.hour,
      t.minute,
    ).add(Duration(minutes: min));
    return TimeOfDay(hour: dt.hour, minute: dt.minute);
  }

  // 最大深度制限付き組み合わせ
  List<List<int>> _findCombinations(int total, List<int> sizes, int maxDepth) {
    List<List<int>> results = [];
    void search(int remain, List<int> current) {
      if (current.length > maxDepth) return;
      if (remain == 0) {
        results.add(List.from(current));
        return;
      }
      for (final s in sizes) {
        if (remain >= s) {
          current.add(s);
          search(remain - s, current);
          current.removeLast();
        }
      }
    }

    search(total, []);
    results.sort((a, b) => a.length.compareTo(b.length));
    return results;
  }

  @override
  Widget build(BuildContext context) {
    super.build(context);
    final provider = Provider.of<RoastScheduleFormProvider>(context);
    final beans = provider.beans;
    final beige = const Color(0xFFFFF8E1);
    final brown = const Color(0xFF795548);
    return Container(
      color: Theme.of(context).scaffoldBackgroundColor,
      child: SingleChildScrollView(
        padding: EdgeInsets.all(16),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            // ★ ここから追加: スケジュール自動作成用入力フォーム
            Card(
              elevation: 6,
              shape: RoundedRectangleBorder(
                borderRadius: BorderRadius.circular(16),
              ),
              color:
                  Provider.of<ThemeSettings>(context).backgroundColor2 ??
                  Colors.white,
              child: Padding(
                padding: const EdgeInsets.all(20),
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    Row(
                      children: [
                        Icon(Icons.edit, color: brown, size: 24),
                        SizedBox(width: 8),
                        Text(
                          'スケジュール自動作成用入力フォーム',
                          style: TextStyle(
                            fontWeight: FontWeight.bold,
                            fontSize: 18,
                            color: brown,
                          ),
                        ),
                      ],
                    ),
                    SizedBox(height: 16),
                    ListView.builder(
                      shrinkWrap: true,
                      physics: NeverScrollableScrollPhysics(),
                      itemCount: beans.length,
                      itemBuilder: (context, i) =>
                          _buildBeanInputRow(beans[i], i),
                    ),
                    SizedBox(height: 16),
                    SizedBox(
                      width: double.infinity,
                      child: ElevatedButton.icon(
                        icon: Icon(Icons.add),
                        label: Text('リストを追加'),
                        style: ElevatedButton.styleFrom(
                          backgroundColor:
                              Theme.of(context)
                                  .elevatedButtonTheme
                                  .style
                                  ?.backgroundColor
                                  ?.resolve({}) ??
                              Theme.of(context).colorScheme.primary,
                          foregroundColor:
                              Theme.of(context)
                                  .elevatedButtonTheme
                                  .style
                                  ?.foregroundColor
                                  ?.resolve({}) ??
                              Colors.white,
                          shape: RoundedRectangleBorder(
                            borderRadius: BorderRadius.circular(12),
                          ),
                          padding: EdgeInsets.symmetric(vertical: 14),
                          textStyle: TextStyle(
                            fontSize: 15,
                            fontWeight: FontWeight.bold,
                          ),
                          elevation: 4,
                        ),
                        onPressed: _addBean,
                      ),
                    ),
                  ],
                ),
              ),
            ),
            SizedBox(height: 16),
            // ★ ここまで追加
            Card(
              elevation: 6,
              shape: RoundedRectangleBorder(
                borderRadius: BorderRadius.circular(16),
              ),
              color:
                  Provider.of<ThemeSettings>(context).backgroundColor2 ??
                  Colors.white,
              child: Padding(
                padding: EdgeInsets.all(20),
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    Row(
                      children: [
                        Icon(Icons.access_time, color: brown, size: 24),
                        SizedBox(width: 8),
                        Text(
                          '焙煎開始時刻',
                          style: TextStyle(
                            fontWeight: FontWeight.bold,
                            fontSize: 18,
                            color: brown,
                          ),
                        ),
                      ],
                    ),
                    SizedBox(height: 16),
                    // --- 焙煎開始時刻エリア ---
                    Stack(
                      children: [
                        Row(
                          children: [
                            Text(
                              '午前:',
                              style: TextStyle(color: brown, fontSize: 15),
                            ),
                            SizedBox(width: 8),
                            ElevatedButton(
                              onPressed: () => _pickTime(true),
                              style: ElevatedButton.styleFrom(
                                backgroundColor:
                                    Theme.of(context)
                                        .elevatedButtonTheme
                                        .style
                                        ?.backgroundColor
                                        ?.resolve({}) ??
                                    Theme.of(context).colorScheme.primary,
                                foregroundColor:
                                    Theme.of(context)
                                        .elevatedButtonTheme
                                        .style
                                        ?.foregroundColor
                                        ?.resolve({}) ??
                                    Colors.white,
                                shape: RoundedRectangleBorder(
                                  borderRadius: BorderRadius.circular(10),
                                ),
                                padding: EdgeInsets.symmetric(
                                  horizontal: 16,
                                  vertical: 10,
                                ),
                              ),
                              child: Text(
                                _amStart == null
                                    ? '選択'
                                    : _amStart!.format(context),
                                style: TextStyle(fontSize: 14),
                              ),
                            ),
                            SizedBox(width: 24),
                            Text(
                              '午後:',
                              style: TextStyle(color: brown, fontSize: 15),
                            ),
                            SizedBox(width: 8),
                            ElevatedButton(
                              onPressed: () => _pickTime(false),
                              style: ElevatedButton.styleFrom(
                                backgroundColor:
                                    Theme.of(context)
                                        .elevatedButtonTheme
                                        .style
                                        ?.backgroundColor
                                        ?.resolve({}) ??
                                    Theme.of(context).colorScheme.primary,
                                foregroundColor:
                                    Theme.of(context)
                                        .elevatedButtonTheme
                                        .style
                                        ?.foregroundColor
                                        ?.resolve({}) ??
                                    Colors.white,
                                shape: RoundedRectangleBorder(
                                  borderRadius: BorderRadius.circular(10),
                                ),
                                padding: EdgeInsets.symmetric(
                                  horizontal: 16,
                                  vertical: 10,
                                ),
                              ),
                              child: Text(
                                _pmStart == null
                                    ? '選択'
                                    : _pmStart!.format(context),
                                style: TextStyle(fontSize: 14),
                              ),
                            ),
                          ],
                        ),
                        Positioned(
                          top: -8,
                          right: 0,
                          child: IconButton(
                            icon: Icon(
                              Icons.refresh,
                              color: Colors.grey,
                              size: 22,
                            ),
                            tooltip: '午前・午後の時刻をリセット',
                            onPressed: () {
                              setState(() {
                                _amStart = null;
                                _pmStart = null;
                              });
                            },
                          ),
                        ),
                      ],
                    ),
                  ],
                ),
              ),
            ),
            SizedBox(height: 16),
            Center(
              child: ElevatedButton.icon(
                onPressed: _generateSchedule,
                icon: Icon(Icons.auto_awesome),
                label: Text('スケジュール自動作成'),
                style: ElevatedButton.styleFrom(
                  backgroundColor: Color(0xFFFF8225),
                  foregroundColor: Colors.white,
                  shape: RoundedRectangleBorder(
                    borderRadius: BorderRadius.circular(12),
                  ),
                  padding: EdgeInsets.symmetric(horizontal: 32, vertical: 14),
                  textStyle: TextStyle(
                    fontWeight: FontWeight.bold,
                    fontSize: 15,
                  ),
                  elevation: 4,
                ),
              ),
            ),
            if (_inputErrorMsg.isNotEmpty)
              Padding(
                padding: EdgeInsets.only(top: 8),
                child: Text(
                  _inputErrorMsg,
                  style: TextStyle(color: Colors.red),
                ),
              ),
            if (_overflowMsg.isNotEmpty)
              Padding(
                padding: EdgeInsets.only(top: 8),
                child: Text(_overflowMsg, style: TextStyle(color: Colors.red)),
              ),
            SizedBox(height: 20),
            if (_inputErrorMsg.isEmpty) ...[
              if (_futureResult != null)
                FutureBuilder<RoastScheduleData>(
                  future: _futureResult,
                  builder: (context, snapshot) {
                    if (snapshot.connectionState == ConnectionState.waiting) {
                      return Center(child: CircularProgressIndicator());
                    }
                    if (snapshot.hasError) {
                      return Text(
                        'スケジュール生成中にエラーが発生しました。',
                        style: TextStyle(color: Colors.red),
                      );
                    }
                    if (!snapshot.hasData) return SizedBox();
                    final data = snapshot.data!;
                    // --- スケジュール表示 ---
                    return _buildScheduleWidgets(
                      context,
                      data.amResult,
                      data.pmResult,
                      data.overflowMsg,
                      brown,
                    );
                  },
                )
              else if (_savedSchedule.isNotEmpty || _savedPmSchedule.isNotEmpty)
                _buildSavedScheduleWidgets(context, brown)
              else
                SizedBox(),
            ],
          ],
        ),
      ),
    );
  }

  // --- 追加: スケジュール表示ウィジェット ---
  Widget _buildScheduleWidgets(
    BuildContext context,
    List<RoastScheduleResult> amResult,
    List<RoastScheduleResult> pmResult,
    String overflowMsg,
    Color brown,
  ) {
    List<Widget> scheduleWidgets = [];
    // 午前
    if (_amStart != null && amResult.isNotEmpty) {
      scheduleWidgets.add(
        Card(
          elevation: 4,
          shape: RoundedRectangleBorder(
            borderRadius: BorderRadius.circular(16),
          ),
          color: Color(0xFFFFF3E0), // 淡いオレンジ
          margin: EdgeInsets.only(bottom: 12),
          child: ListTile(
            contentPadding: EdgeInsets.symmetric(horizontal: 20, vertical: 8),
            leading: Icon(
              Icons.local_fire_department,
              color: Color(0xFFFF8225),
              size: 28,
            ),
            title: Text(
              '${_amStart!.format(context)} 焙煎機予熱開始',
              style: TextStyle(
                fontWeight: FontWeight.bold,
                fontSize: 16,
                color: brown,
              ),
            ),
          ),
        ),
      );
      for (final r in amResult) {
        if (r.afterPurge) {
          scheduleWidgets.add(
            Card(
              elevation: 4,
              shape: RoundedRectangleBorder(
                borderRadius: BorderRadius.circular(16),
              ),
              color: Colors.blueGrey[50],
              margin: EdgeInsets.only(bottom: 12),
              child: ListTile(
                contentPadding: EdgeInsets.symmetric(
                  horizontal: 20,
                  vertical: 8,
                ),
                leading: Icon(Icons.ac_unit, color: Colors.blue, size: 28),
                title: Text(
                  'アフターパージを実行',
                  style: TextStyle(color: brown, fontWeight: FontWeight.bold),
                ),
              ),
            ),
          );
        } else {
          scheduleWidgets.add(
            Card(
              elevation: 4,
              shape: RoundedRectangleBorder(
                borderRadius: BorderRadius.circular(16),
              ),
              color: Colors.white, // ← ここをデフォルト色に固定
              margin: EdgeInsets.only(bottom: 12),
              child: ListTile(
                contentPadding: EdgeInsets.symmetric(
                  horizontal: 20,
                  vertical: 8,
                ),
                leading: r.task != null
                    ? CircleAvatar(
                        backgroundColor: Color(0xFFFFF8E1),
                        child: Text(
                          _roastIcons[r.task!.roastLevel] ?? '☕',
                          style: TextStyle(fontSize: 20),
                        ),
                      )
                    : null,
                title: Row(
                  children: [
                    if (r.time != null)
                      Text(
                        r.time!.format(context),
                        style: TextStyle(
                          fontWeight: FontWeight.bold,
                          color: brown,
                          fontSize: 16,
                        ),
                      ),
                    SizedBox(width: 12),
                    Expanded(
                      child: Text(
                        '${r.task?.type ?? ''} '
                        '${r.task?.weights.map((w) => '${w}g').join('・') ?? ''}',
                        style: TextStyle(
                          fontWeight: FontWeight.bold,
                          color: Color(0xFF2C1D17),
                        ),
                      ),
                    ),
                  ],
                ),
                subtitle: r.task != null && r.task!.roastLevel.isNotEmpty
                    ? Text(
                        r.task!.roastLevel,
                        style: TextStyle(
                          color: brown,
                          fontWeight: FontWeight.w500,
                        ),
                      )
                    : null,
              ),
            ),
          );
        }
      }
    }
    // 午後予熱開始
    if (_pmStart != null && pmResult.isNotEmpty) {
      scheduleWidgets.add(
        Card(
          elevation: 4,
          shape: RoundedRectangleBorder(
            borderRadius: BorderRadius.circular(16),
          ),
          color: Color(0xFFFFF3E0),
          margin: EdgeInsets.only(top: 16, bottom: 12),
          child: ListTile(
            contentPadding: EdgeInsets.symmetric(horizontal: 20, vertical: 8),
            leading: Icon(
              Icons.local_fire_department,
              color: Color(0xFFFF8225),
              size: 28,
            ),
            title: Text(
              '${_pmStart!.format(context)} 焙煎機予熱開始',
              style: TextStyle(
                fontWeight: FontWeight.bold,
                fontSize: 16,
                color: brown,
              ),
            ),
          ),
        ),
      );
      for (final r in pmResult) {
        if (r.afterPurge) {
          scheduleWidgets.add(
            Card(
              elevation: 4,
              shape: RoundedRectangleBorder(
                borderRadius: BorderRadius.circular(16),
              ),
              color: Colors.blueGrey[50],
              margin: EdgeInsets.only(bottom: 12),
              child: ListTile(
                contentPadding: EdgeInsets.symmetric(
                  horizontal: 20,
                  vertical: 8,
                ),
                leading: Icon(Icons.ac_unit, color: Colors.blue, size: 28),
                title: Text(
                  'アフターパージを実行',
                  style: TextStyle(color: brown, fontWeight: FontWeight.bold),
                ),
              ),
            ),
          );
        } else {
          scheduleWidgets.add(
            Card(
              elevation: 4,
              shape: RoundedRectangleBorder(
                borderRadius: BorderRadius.circular(16),
              ),
              color: Colors.white, // ← ここもデフォルト色に固定
              margin: EdgeInsets.only(bottom: 12),
              child: ListTile(
                contentPadding: EdgeInsets.symmetric(
                  horizontal: 20,
                  vertical: 8,
                ),
                leading: r.task != null
                    ? CircleAvatar(
                        backgroundColor: Color(0xFFFFF8E1),
                        child: Text(
                          _roastIcons[r.task!.roastLevel] ?? '☕',
                          style: TextStyle(fontSize: 20),
                        ),
                      )
                    : null,
                title: Row(
                  children: [
                    if (r.time != null)
                      Text(
                        r.time!.format(context),
                        style: TextStyle(
                          fontWeight: FontWeight.bold,
                          color: brown,
                          fontSize: 16,
                        ),
                      ),
                    SizedBox(width: 12),
                    Expanded(
                      child: Text(
                        '${r.task?.type ?? ''} '
                        '${r.task?.weights.map((w) => '${w}g').join('・') ?? ''}',
                        style: TextStyle(
                          fontWeight: FontWeight.bold,
                          color: Color(0xFF2C1D17),
                        ),
                      ),
                    ),
                  ],
                ),
                subtitle: r.task != null && r.task!.roastLevel.isNotEmpty
                    ? Text(
                        r.task!.roastLevel,
                        style: TextStyle(
                          color: brown,
                          fontWeight: FontWeight.w500,
                        ),
                      )
                    : null,
              ),
            ),
          );
        }
      }
    }
    if (overflowMsg.isNotEmpty) {
      scheduleWidgets.add(
        Padding(
          padding: EdgeInsets.only(top: 8),
          child: Text(overflowMsg, style: TextStyle(color: Colors.red)),
        ),
      );
    }
    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: scheduleWidgets,
    );
  }

  // --- 追加: 保存済みスケジュールの表示 ---
  Widget _buildSavedScheduleWidgets(BuildContext context, Color brown) {
    List<Widget> scheduleWidgets = [];
    // 午前
    if (_amStart != null) {
      scheduleWidgets.add(
        Card(
          elevation: 4,
          shape: RoundedRectangleBorder(
            borderRadius: BorderRadius.circular(16),
          ),
          color: Color(0xFFFFF3E0),
          margin: EdgeInsets.only(bottom: 12),
          child: ListTile(
            contentPadding: EdgeInsets.symmetric(horizontal: 20, vertical: 8),
            leading: Icon(
              Icons.local_fire_department,
              color: Color(0xFFFF8225),
              size: 28,
            ),
            title: Text(
              '${_amStart!.format(context)} 焙煎機予熱開始',
              style: TextStyle(
                fontWeight: FontWeight.bold,
                fontSize: 16,
                color: brown,
              ),
            ),
          ),
        ),
      );
    }
    // 午後
    if (_pmStart != null) {
      scheduleWidgets.add(
        Card(
          elevation: 4,
          shape: RoundedRectangleBorder(
            borderRadius: BorderRadius.circular(16),
          ),
          color: Color(0xFFFFF3E0),
          margin: EdgeInsets.only(top: 16, bottom: 12),
          child: ListTile(
            contentPadding: EdgeInsets.symmetric(horizontal: 20, vertical: 8),
            leading: Icon(
              Icons.local_fire_department,
              color: Color(0xFFFF8225),
              size: 28,
            ),
            title: Text(
              '${_pmStart!.format(context)} 焙煎機予熱開始',
              style: TextStyle(
                fontWeight: FontWeight.bold,
                fontSize: 16,
                color: brown,
              ),
            ),
          ),
        ),
      );
    }
    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        Padding(
          padding: EdgeInsets.only(bottom: 8),
          child: Text(
            '保存済みスケジュール',
            style: TextStyle(
              fontWeight: FontWeight.bold,
              fontSize: 16,
              color: brown,
            ),
          ),
        ),
        ...scheduleWidgets,
      ],
    );
  }

  // --- 入力内容の保存・復元 ---
  Future<void> _saveInputState() async {
    try {
      final prefs = await SharedPreferences.getInstance();
      final provider = Provider.of<RoastScheduleFormProvider>(
        context,
        listen: false,
      );
      final beansList = provider.beans.map((b) => b.toJson()).toList();
      await prefs.setString('roastInput_beans', json.encode(beansList));
      await prefs.setString(
        'roastInput_am',
        _amStart != null ? '${_amStart!.hour}:${_amStart!.minute}' : '',
      );
      await prefs.setString(
        'roastInput_pm',
        _pmStart != null ? '${_pmStart!.hour}:${_pmStart!.minute}' : '',
      );
    } catch (_) {}
  }

  Future<void> _restoreInputState() async {
    try {
      final prefs = await SharedPreferences.getInstance();
      final provider = Provider.of<RoastScheduleFormProvider>(
        context,
        listen: false,
      );
      final beansJson = prefs.getString('roastInput_beans');
      if (beansJson != null) {
        final List<dynamic> beansList = json.decode(beansJson);
        setState(() {
          provider.beans = beansList
              .map<RoastScheduleBean>((e) => RoastScheduleBean.fromJson(e))
              .toList();
          if (provider.beans.isEmpty) {
            provider.addBean(RoastScheduleBean(name: '', weight: 0));
          }
        });
      }
      final amStr = prefs.getString('roastInput_am');
      if (amStr != null && amStr.isNotEmpty) {
        final parts = amStr.split(':');
        if (parts.length == 2) {
          setState(() {
            _amStart = TimeOfDay(
              hour: int.parse(parts[0]),
              minute: int.parse(parts[1]),
            );
          });
        }
      }
      final pmStr = prefs.getString('roastInput_pm');
      if (pmStr != null && pmStr.isNotEmpty) {
        final parts = pmStr.split(':');
        if (parts.length == 2) {
          setState(() {
            _pmStart = TimeOfDay(
              hour: int.parse(parts[0]),
              minute: int.parse(parts[1]),
            );
          });
        }
      }
    } catch (_) {}
  }

  Widget _buildBeanInputRow(RoastScheduleBean bean, int index) {
    final provider = Provider.of<RoastScheduleFormProvider>(
      context,
      listen: false,
    );
    final brown = const Color(0xFF795548);
    return Card(
      elevation: 4,
      shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(16)),
      color:
          Provider.of<ThemeSettings>(context).backgroundColor2 ?? Colors.white,
      margin: EdgeInsets.only(bottom: 16),
      child: Padding(
        padding: const EdgeInsets.all(20),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            // 1行目：豆の名前・重量
            Row(
              crossAxisAlignment: CrossAxisAlignment.center,
              children: [
                Icon(Icons.coffee, color: brown, size: 20),
                SizedBox(width: 8),
                Expanded(
                  child: Column(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: [
                      Text(
                        '豆の名前',
                        style: TextStyle(
                          color: brown,
                          fontWeight: FontWeight.bold,
                          fontSize: 14,
                        ),
                      ),
                      SizedBox(height: 6),
                      TextFormField(
                        initialValue: bean.name,
                        decoration: InputDecoration(
                          isDense: true,
                          contentPadding: EdgeInsets.symmetric(
                            vertical: 12,
                            horizontal: 14,
                          ),
                          border: OutlineInputBorder(
                            borderRadius: BorderRadius.circular(10),
                            borderSide: BorderSide(color: Colors.grey.shade300),
                          ),
                          enabledBorder: OutlineInputBorder(
                            borderRadius: BorderRadius.circular(10),
                            borderSide: BorderSide(color: Colors.grey.shade300),
                          ),
                          focusedBorder: OutlineInputBorder(
                            borderRadius: BorderRadius.circular(10),
                            borderSide: BorderSide(color: brown, width: 2),
                          ),
                          filled: true,
                          fillColor: Colors.grey.shade50,
                        ),
                        onChanged: (val) {
                          provider.updateBean(
                            index,
                            RoastScheduleBean(
                              name: val,
                              weight: bean.weight,
                              bags: bean.bags,
                              roastLevel: bean.roastLevel,
                            ),
                          );
                        },
                      ),
                    ],
                  ),
                ),
                SizedBox(width: 20),
                Icon(Icons.scale, color: brown, size: 20),
                SizedBox(width: 8),
                SizedBox(
                  width: 100,
                  child: Column(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: [
                      Text(
                        '重量',
                        style: TextStyle(
                          color: brown,
                          fontWeight: FontWeight.bold,
                          fontSize: 14,
                        ),
                      ),
                      SizedBox(height: 6),
                      TextFormField(
                        initialValue: bean.weight.toString(),
                        decoration: InputDecoration(
                          isDense: true,
                          contentPadding: EdgeInsets.symmetric(
                            vertical: 12,
                            horizontal: 14,
                          ),
                          border: OutlineInputBorder(
                            borderRadius: BorderRadius.circular(10),
                            borderSide: BorderSide(color: Colors.grey.shade300),
                          ),
                          enabledBorder: OutlineInputBorder(
                            borderRadius: BorderRadius.circular(10),
                            borderSide: BorderSide(color: Colors.grey.shade300),
                          ),
                          focusedBorder: OutlineInputBorder(
                            borderRadius: BorderRadius.circular(10),
                            borderSide: BorderSide(color: brown, width: 2),
                          ),
                          filled: true,
                          fillColor: Colors.grey.shade50,
                        ),
                        keyboardType: TextInputType.number,
                        onChanged: (val) {
                          final weight = int.tryParse(val) ?? 0;
                          provider.updateBean(
                            index,
                            RoastScheduleBean(
                              name: bean.name,
                              weight: weight,
                              bags: bean.bags,
                              roastLevel: bean.roastLevel,
                            ),
                          );
                        },
                      ),
                    ],
                  ),
                ),
              ],
            ),
            SizedBox(height: 16),
            // 2行目：袋数・焙煎度合い・削除ボタン
            Row(
              crossAxisAlignment: CrossAxisAlignment.center,
              children: [
                Icon(Icons.shopping_bag, color: brown, size: 20),
                SizedBox(width: 8),
                SizedBox(
                  width: 80,
                  child: Column(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: [
                      Text(
                        '袋数',
                        style: TextStyle(
                          color: brown,
                          fontWeight: FontWeight.bold,
                          fontSize: 14,
                        ),
                      ),
                      SizedBox(height: 6),
                      TextFormField(
                        initialValue: bean.bags?.toString() ?? '',
                        decoration: InputDecoration(
                          isDense: true,
                          contentPadding: EdgeInsets.symmetric(
                            vertical: 12,
                            horizontal: 14,
                          ),
                          border: OutlineInputBorder(
                            borderRadius: BorderRadius.circular(10),
                            borderSide: BorderSide(color: Colors.grey.shade300),
                          ),
                          enabledBorder: OutlineInputBorder(
                            borderRadius: BorderRadius.circular(10),
                            borderSide: BorderSide(color: Colors.grey.shade300),
                          ),
                          focusedBorder: OutlineInputBorder(
                            borderRadius: BorderRadius.circular(10),
                            borderSide: BorderSide(color: brown, width: 2),
                          ),
                          filled: true,
                          fillColor: Colors.grey.shade50,
                        ),
                        keyboardType: TextInputType.number,
                        onChanged: (val) {
                          final bags = int.tryParse(val);
                          provider.updateBean(
                            index,
                            RoastScheduleBean(
                              name: bean.name,
                              weight: bean.weight,
                              bags: bags,
                              roastLevel: bean.roastLevel,
                            ),
                          );
                        },
                      ),
                    ],
                  ),
                ),
                SizedBox(width: 16),
                Icon(Icons.local_fire_department, color: brown, size: 20),
                SizedBox(width: 8),
                Expanded(
                  child: Column(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: [
                      Text(
                        '焙煎度合い',
                        style: TextStyle(
                          color: brown,
                          fontWeight: FontWeight.bold,
                          fontSize: 14,
                        ),
                      ),
                      SizedBox(height: 6),
                      DropdownButtonFormField<String>(
                        value: bean.roastLevel,
                        decoration: InputDecoration(
                          isDense: true,
                          contentPadding: EdgeInsets.symmetric(
                            vertical: 12,
                            horizontal: 14,
                          ),
                          border: OutlineInputBorder(
                            borderRadius: BorderRadius.circular(10),
                            borderSide: BorderSide(color: Colors.grey.shade300),
                          ),
                          enabledBorder: OutlineInputBorder(
                            borderRadius: BorderRadius.circular(10),
                            borderSide: BorderSide(color: Colors.grey.shade300),
                          ),
                          focusedBorder: OutlineInputBorder(
                            borderRadius: BorderRadius.circular(10),
                            borderSide: BorderSide(color: brown, width: 2),
                          ),
                          filled: true,
                          fillColor: Colors.grey.shade50,
                        ),
                        items: ['浅煎り', '中煎り', '中深煎り', '深煎り']
                            .map(
                              (e) => DropdownMenuItem(value: e, child: Text(e)),
                            )
                            .toList(),
                        onChanged: (val) {
                          provider.updateBean(
                            index,
                            RoastScheduleBean(
                              name: bean.name,
                              weight: bean.weight,
                              bags: bean.bags,
                              roastLevel: val,
                            ),
                          );
                        },
                      ),
                    ],
                  ),
                ),
                if (index != 0)
                  IconButton(
                    icon: Icon(
                      Icons.remove_circle,
                      color: Colors.red,
                      size: 28,
                    ),
                    onPressed: () => _removeBean(index),
                    iconSize: 28,
                    padding: EdgeInsets.all(8),
                  ),
              ],
            ),
          ],
        ),
      ),
    );
  }

  RoastBreakTime? _findBreak(TimeOfDay t) {
    for (final b in widget.breakTimes) {
      final tMinutes = t.hour * 60 + t.minute;
      final breakStart = b.start.hour * 60 + b.start.minute;
      if (tMinutes >= (breakStart - 10) &&
          tMinutes < b.end.hour * 60 + b.end.minute) {
        return b;
      }
    }
    return null;
  }

  // Firestore同期用setter
  void setScheduleFromFirestore(Map<String, dynamic> schedule) {
    setState(() {
      final amList = schedule['am'] as List<dynamic>? ?? [];
      final pmList = schedule['pm'] as List<dynamic>? ?? [];
      _savedSchedule = amList
          .map(
            (e) =>
                RoastScheduleResultModel.fromJson(Map<String, dynamic>.from(e)),
          )
          .toList();
      _savedPmSchedule = pmList
          .map(
            (e) =>
                RoastScheduleResultModel.fromJson(Map<String, dynamic>.from(e)),
          )
          .toList();
      _savedOverflowMsg = schedule['overflowMsg'] as String? ?? '';
    });
  }

  @override
  bool get wantKeepAlive => true;
}
